/*
 * This file is generated by jOOQ.
 */
package io.sakila.actor.db.tables.records;


import io.sakila.actor.db.tables.Actor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorRecord extends UpdatableRecordImpl<ActorRecord> implements Record7<UUID, String, String, String, String, LocalDate, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.actor.actor_id</code>.
     */
    public void setActorId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.actor.actor_id</code>.
     */
    public UUID getActorId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.actor.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.actor.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.actor.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.actor.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.actor.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.actor.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.actor.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.actor.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.actor.dob</code>.
     */
    public void setDob(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.actor.dob</code>.
     */
    public LocalDate getDob() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.actor.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.actor.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, String, String, String, LocalDate, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, String, String, String, String, LocalDate, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Actor.ACTOR.ACTOR_ID;
    }

    @Override
    public Field<String> field2() {
        return Actor.ACTOR.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Actor.ACTOR.LAST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Actor.ACTOR.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Actor.ACTOR.PHONE_NUMBER;
    }

    @Override
    public Field<LocalDate> field6() {
        return Actor.ACTOR.DOB;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Actor.ACTOR.LAST_UPDATE;
    }

    @Override
    public UUID component1() {
        return getActorId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getPhoneNumber();
    }

    @Override
    public LocalDate component6() {
        return getDob();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdate();
    }

    @Override
    public UUID value1() {
        return getActorId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getPhoneNumber();
    }

    @Override
    public LocalDate value6() {
        return getDob();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdate();
    }

    @Override
    public ActorRecord value1(UUID value) {
        setActorId(value);
        return this;
    }

    @Override
    public ActorRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ActorRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ActorRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public ActorRecord value5(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public ActorRecord value6(LocalDate value) {
        setDob(value);
        return this;
    }

    @Override
    public ActorRecord value7(LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public ActorRecord values(UUID value1, String value2, String value3, String value4, String value5, LocalDate value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActorRecord
     */
    public ActorRecord() {
        super(Actor.ACTOR);
    }

    /**
     * Create a detached, initialised ActorRecord
     */
    public ActorRecord(UUID actorId, String firstName, String lastName, String email, String phoneNumber, LocalDate dob, LocalDateTime lastUpdate) {
        super(Actor.ACTOR);

        setActorId(actorId);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setPhoneNumber(phoneNumber);
        setDob(dob);
        setLastUpdate(lastUpdate);
    }
}
